language: java
jdk:
- openjdk8
install: cd Hello && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
script: mvn test
before_install:
  - openssl aes-256-cbc -K $encrypted_9655a05d2431_key -iv $encrypted_9655a05d2431_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 111.231.1.210
